[project]
name = "zigup"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Gaines", email = "me@jgaines.com" }
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
zigup = "zigup:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "zigup.py"

[dependency-groups]
dev = [
    "ipython>=8.31.0",
]
